# flowers dataset
flowers_images_path: './Data/jpg/'
flowers_text_path: './Data/text_c10/'
flowers_dataset_path: './Data/flowers.hdf5'
flowers_val_split_path: './Data/valclasses.txt'
flowers_train_split_path: './Data/trainclasses.txt'
flowers_test_split_path: './Data/testclasses.txt'